from typing import Annotated, Optional
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    latest_speaker: Annotated[str, "Latest speaker: 'Bull' | 'Bear' | 'Manager'"]
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    macro_report: Annotated[str, "Report from the Macroeconomic Analyst"] = ""
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    market_context: Annotated[str, "Market environment context for the analysis date"] = ""

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
    knowledge_context: Annotated[
        dict,
        "Structured knowledge context assembled at run start. "
        "Contains archived_analyses, past_decisions, ticker_signals, lessons. "
        "Each agent extracts what it needs.",
    ] = {}

    # A股特有字段（可选，美股场景不填）
    market_type: Annotated[str, "Market type: 'A_SHARE' or 'US_STOCK'"] = "A_SHARE"
    benchmark_ticker: Annotated[str, "Benchmark index for alpha calculation"] = "000300"
    position_opened_date: Annotated[str, "Date when current position was opened"] = ""
    limit_up_price: Annotated[float, "A-share daily limit-up price"] = 0.0
    limit_down_price: Annotated[float, "A-share daily limit-down price"] = 0.0

    # Position tracking fields
    cost_price: Annotated[float, "Average cost price of current position"] = 0.0
    quantity: Annotated[int, "Number of shares held"] = 0
    position_pnl: Annotated[float, "Unrealized P&L amount in quote currency"] = 0.0
    position_pnl_pct: Annotated[Optional[float], "Unrealized P&L percentage (None for zero-cost)"] = None
